server:
  port: 8000
spring:
  datasource:
    druid:
      aop-patterns: com.yan.helloword.*
      filters: stat,wall
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root